version: "3.7" 
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports: 
      - "8080:80"
    volumes: 
      - ".:/var/www/html/"
      - "./webserver/nginx.conf:/etc/nginx/nginx.conf"
    links:
      - php
      - mysql
  php:
    build:
      context: .
    image: phpdocker
    container_name: php
    ports:
      - "9000:9000"
    volumes:
      - ".:/var/www/html/" 
  mysql:
    image: mysql:5.7
    container_name: mysql
    ports: 
      - "3307:3306"
    volumes: 
      - mysql:/var/lib/mysql
    environment: 
      MYSQL_DATABASE: 'database'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: '12345'
volumes: 
  mysql:

