version: "3.7" 
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports: 
      - "8080:80"
    volumes: 
      - ".:/var/www/html/"
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
    links:
      - php
      - mysql
    networks:
      - mysql-compose-network

  php:
    build:
      context: .
    image: phpdocker
    container_name: php
    ports:
      - "9000:9000"
    volumes:
      - ".:/var/www/html/" 
      - "./php/php.ini:/usr/local/etc/php/php.ini"
    networks:
      - mysql-compose-network

  mysql:
    image: mysql:5.7
    container_name: mysql
    ports: 
      - "3307:3306"
    volumes: 
      - "./mysql/data:/var/lib/mysql"
      - "./mysql/log:/var/log/mysql"
      - "./mysql/conf:/etc/mysql/conf.d"
    environment: 
      MYSQL_DATABASE: "database"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "12345"
      MYSQL_ROOT_PASSWORD: "12345"
    networks:
      - mysql-compose-network

networks:
  mysql-compose-network:
    driver: "bridge"

volumes: 
  mysql:


